spring:
  jpa:
    #是否显示sql
    show-sql: true
    #指定数据库类型
    database: mysql
    #方言
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    #自动建表方式
    hibernate:
      ddl-auto: update
    #格式化sql
    properties:
      hibernate:
        format-sql: true
  #数据库驱动
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
<<<<<<< HEAD
    password: 123456
    url: jdbc:mysql://192.168.124.6:3306/gjj?characterEncoding=utf-8&useUnicode=true&useSSL=true&serverTimezone=UTC
=======
    password: yzh
    url: jdbc:mysql://localhost:3306/group?characterEncoding=utf-8&useUnicode=true&useSSL=true&serverTimezone=UTC

  #thymeleaf模板配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    #关掉缓存
    cache: false
    password:
    url: jdbc:mysql://123:3306/gjj?characterEncoding=utf-8
  #thymeleaf模板配置
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
#    mode: HTML5
#    encoding: UTF-8
#    servlet:
#      content-type: text/html
#    #关掉缓存
#    cache: false
>>>>>>> ab1913818a7217b24a49b212ef5a6f6a4c31e399
    type: com.alibaba.druid.pool.DruidDataSource
    tomcat:
      max-active: 20
      max-wait: 60000
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
server:
  port: 8080