spring:
  jpa:
    #是否显示sql
    show-sql: true
    #指定数据库类型
    database: mysql
    #方言
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    #自动建表方式
    hibernate:
      ddl-auto: update
    #格式化sql
    properties:
      hibernate:
        format-sql: true
  #数据库驱动
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.124.6:3306/gjj?characterEncoding=utf-8&useUnicode=true&useSSL=true&serverTimezone=UTC
  #thymeleaf模板配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    #关掉缓存
    cache: false
  #所有/**请求的静态资源都会被处理
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
server:
  port: 8080