spring:
  jpa:
    #是否显示sql
    show-sql: true
    #指定数据库类型
    database: mysql
    #方言
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    #自动建表方式
    hibernate:
      ddl-auto: update
    #格式化sql
    properties:
      hibernate:
        format-sql: true
  #数据库驱动
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
server:
  port: 8081